CREATE DATABASE `analytics` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE `page_statistics` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `added` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `method` varchar(45) DEFAULT NULL,
  `server_name` varchar(45) DEFAULT NULL,
  `pre_url` varchar(255) DEFAULT NULL,
  `post_url` varchar(255) DEFAULT NULL,
  `query_string` varchar(255) DEFAULT NULL,
  `http_response_code` int DEFAULT NULL,
  `load_time` decimal(10,6) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `server_port` int DEFAULT NULL,
  `bytes_request` int DEFAULT NULL,
  `bytes_response` int DEFAULT NULL,
  `ip_address` varchar(15) NOT NULL,
  `host_name` varchar(255) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `referer` varchar(255) DEFAULT NULL,
  `cookie` varchar(255) DEFAULT NULL,
  `htaccess_user` varchar(45) DEFAULT NULL,
  `source_file` varchar(255) NOT NULL,
  `line_number` int NOT NULL,
  `line` text NOT NULL,
  PRIMARY KEY (`source_file`,`line_number`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `hits` (`server_name`,`pre_url`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci KEY_BLOCK_SIZE=8;

CREATE TABLE `page_statistics` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `added` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `method` varchar(45) DEFAULT NULL,
  `server_name` varchar(45) DEFAULT NULL,
  `pre_url` varchar(255) DEFAULT NULL,
  `post_url` varchar(255) DEFAULT NULL,
  `query_string` varchar(255) DEFAULT NULL,
  `http_response_code` int DEFAULT NULL,
  `load_time` decimal(10,6) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `server_port` int DEFAULT NULL,
  `bytes_request` int DEFAULT NULL,
  `bytes_response` int DEFAULT NULL,
  `ip_address` varchar(15) NOT NULL,
  `host_name` varchar(255) DEFAULT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  `referer` varchar(255) DEFAULT NULL,
  `cookie` varchar(255) DEFAULT NULL,
  `htaccess_user` varchar(45) DEFAULT NULL,
  `source_file` varchar(255) NOT NULL,
  `line_number` int NOT NULL,
  `line` text NOT NULL,
  PRIMARY KEY (`source_file`,`line_number`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `hits` (`server_name`,`pre_url`)
) ENGINE=InnoDB AUTO_INCREMENT=1085068 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci KEY_BLOCK_SIZE=8;
